### ISSUE TITLE
feature request: support method `patch`

### ISSUE THREAD

**Issue by asnowwolf** [angular/in-memory-web-api#115]
`patch` is a relatively common method, such as github API. Providing mock for `patch` method helps to improve the degree of simulation.

**Comment by wardbell** [comment]
Closing because this is outside the design goals for this library. I might do it someday but there is no compelling need at the moment and it's tricky because of the blending involved and all kinds of edge conditions.

You can easily add it yourself to your own configuration. See section in the README on "HTTP method interceptors".
