### ISSUE TITLE
Support for the new HttpClient of Angular 4.3

### ISSUE THREAD

**Issue by stephanecot** [angular/in-memory-web-api#122]
The current version of in-memory-web-api "mock" the datas used with Http (@angular/http), but the new HttpClient doesn't support this.

**Comment by mmc41** [comment]
Also very interested in HttpClient support!

**Comment by markjritchie** [comment]
Can we have some sort of indication if support for the HttpClient is planned or do we need to look for an alternative solution

**Comment by marcojahn** [comment]
I think it will not needed anymore...
https://angular.io/guide/http#intercepting-all-requests-or-responses

with the new interceptors you can write your own implementation.
https://angular.io/guide/http#caching

The caching example should show you how this behaviour could be implemented

**Comment by stephanecot** [comment]
Before all of that was automatic. I had a objet Foo = { ... }, and all the requests GET/PUT/ etc.... was  supported automatically.
So for you It's the same thing, if I have 20 objets (restfull entities) to support,  to write 20 differents interceptors and all the updates myself ??
In my projects, I mock all my rest api with this api for testing more quickly, It's not just for make a quick test on jsfiddle.
A new version of this component will be easier to write with Interceptor in the same way of the exemple, but there will be some code to add to make as effective as before.

**Comment by mayordwells** [comment]
Please provide support for HttpClient. Please. This is more useful more than the documentation it is intended for. Thank you. @IgorMinar Please look into this.

**Comment by wardbell** [comment]
Completely agree with this request. The in-memory web api is my baby and it should support `HttpClient` ASAP. It is high on my list and I'm sorry that we don't have it already. I will work on this "soon".

**Comment by mayordwells** [comment]
@wardbell thank you very much for your prompt reply. Your clear explanation and instant commitment to this means a lot to me. God bless you. Looking forward to an update asap.

**Comment by daniel-seitz** [comment]
@wardbell You wrote that `there is no way to determine interceptor registration order`. In the Angular docs it says `When you provide multiple interceptors in an application, Angular applies them in the order that you provided them.`

So if there is no way to determine, we could at least define it. That will possibly lead to some issues here because that little info could be forgotten easily but at least it's a way to achieve it.

Source https://angular.io/guide/http#intercepting-all-requests-or-responses in the section Ordering.

**Comment by wardbell** [comment]
You must be able to remove the in-memory web api so that XHR requests go to the true backend and all of your interceptors still work, in the order that you added them. Therefore, it is imperative that the in-memory web api run LAST, _after all of your application interceptors_. 

Fortunately, I know how to do make this happen.

I'm working on this issue _right now_.  You can see my progress in PR #130.

As I write this, I've got tests working on the existing code, something I've been meaning to do _forever_.  I was afraid to refactor to add `HttpClient` support without those tests first.
Now that I have them, I can move on to adding that support.

Stay tuned.

**Comment by wardbell** [comment]
It's done!  See the v0.4.0 (and v.0.4.1) release.

**Comment by daniel-seitz** [comment]
Awesome!
