### ISSUE TITLE
Issue with findObjectById (in path)

### ISSUE THREAD

**Issue by stephanecot** [angular/in-memory-web-api#136]
I have a problem with the url like GET /objects/{id} which now return always null.
The GET /objects work well as before, and returns all my objects.

It was working with the last version 0.3.x, and I thinks  it's maybe because I have an id of type **string** and not **number**.

`protected findById<T extends { id: any }>(collection: T[], id: any): T {`
`    return collection.find((item: T) => item.id === id);`
`}`

the problem seems to be the **===** in my case.

`protected parseId(id: string): any {`
`const idNum = parseFloat(id);`
`return isNaN(idNum) ? id : idNum;`
`}`

For my test, I used id: '1', id: '2'.... but my id is string. Due to the method **parseId()**, my id is cast as a number, and then the **===** of **findById** failed.

**Comment by wardbell** [comment]
**That's my fault**. During my refactor (in 0.4.0, 0.4.1 or 0.4.2) I couldn't remember why I tested the `id` type of an element in the collection so I got rid of that ... and broke you. I need to see if the `id` is a string type and, if it is, not even _attempt_ to parse it as a number.

I will fix that in v.0.4.4.

**Comment by stephanecot** [comment]
No problem, It's seems that I soon find all your bugs ;)

**Comment by wardbell** [comment]
I hope soon.  There were many hidden in there. Testing found some of them. Refactoring for `HttpClient` inadvertently added more.

Note that the fix is itself a breaking change. Previous versions of the library would generate a numeric id for new items POSTed to a collection that was supposed to have string ids.

For example, if your heroes collection had string ids like `100` and you added a new hero without specifying the id, the library would generate an id for you ... and that id would be `1`.

That was _never_ right. What it will now do is throw a `422 - Unprocessable Entity`, on the grounds that you tried to add a new entity without supplying the id.

The presumption of 422 is that it is the requestor's fault, not a system fault.

**Comment by wardbell** [comment]
Released 0.4.4 with fix described above

**Comment by stephanecot** [comment]
For id generator with string id, you, maybe, can make a random string by default ?
I use **chancejs.hash({length:** **10});** by exemple.
