### ISSUE TITLE
Remove @angular/http code and dependency

### ISSUE THREAD

**Issue by Stephane-Peyroutet** [angular/in-memory-web-api#161]
@angular/http references should be removed from code and dependency.
This package has been officialy deprecated since v5 in favor of @angular/common/http.

Currently, other libraries (eg : @angular/material) have removed this dependency but we still need to load this package for in-memory-web-api if we use the latest angular whereas the package has been deprecated.

**Comment by wardbell** [comment]
Supporting the old `HttpModule` so as not to break existing apps that haven't migrated.

You can use the pure `HttpClientInMemoryWebApiModule` instead of the combo module.
`@angular/http` is merely a peer dependency and won't actually be in your code if you do this.
You don't have to install the old Http package.
Moreover, you shouldn't worry about this because the in-memory-web-api is NOT FOR PRODUCTION and so size shouldn't really matter. It's up to you to keep it (and its unwanted dependencies) out of your production build.

Closing because there is a solution.

**Comment by Stephane-Peyroutet** [comment]
I don't know what I am missing but I only reference the HttpClientInMemoryWebApiModule.
As for the @angular/http module, I don't see any good reason to keep a dependency and install a module that is not supposed to be used anywhere.
But when I do remove it, I got an error coming from *.d.ts files.
```

ERROR in node_modules/angular-in-memory-web-api/http-backend.service.d.ts(2,75): error TS2307: Cannot find module '@angular/http'.
node_modules/angular-in-memory-web-api/http-in-memory-web-api.module.d.ts(2,28): error TS2307: Cannot find module '@angular/http'.
```

Could you check this anyway ?

**Comment by xmlking** [comment]
I am forced to do `npm install --save-dev @angular/http@5.1.1` to get red of error mentioned by @Stephane-Peyroutet

**Comment by Stephane-Peyroutet** [comment]
Hey @xmlking, thank you for the backup on this one but I'm not sure this issue will be reopened.
I completely get the "supporting the old HttpModule so as not to break existing apps".
But as I mentioned, this module is deprecated and we will have to do exactly what you did in order to get rid of that error...until that dependency is removed.
That's why I filled this issue...so this would be sooner than later.

**Comment by Springrbua** [comment]
@wardbell I am facing the same Isse (cannot find module @angular/http). Is there a way to fix this issue?

**Comment by haichaom** [comment]
I just cleanup the node_modules, and npm install again.
