### ISSUE TITLE
[Suggestion] Allow response configuration

### ISSUE THREAD

**Issue by mug3n** [angular/in-memory-web-api#74]
An option to change response type would be a nice addition. Example: 
The HTTP spec recommends returning 204 on PUT, as you've implemented. But in practice this recommendation is far from ideal, as it requires another GET request in order to access the processed entity. Now, while I'm all for simple and clean, this is too much. Very few implement this by the spec, especially because having the updated entity in the PUT request response won't break anything.

**Comment by wardbell** [comment]
Many apis do not send the updated entity back on a PUT so that they minimize traffic on the wire, something that is important for many consumer scenarios.

I went back and forth on your request. I decide to keep the default behavior but I added configuration options to PR #79 to achieve what you prefer:
```
  /**
   * true (default) should NOT return the entity (204) after a POST. false: return the entity (200).
   */
  post204?: boolean;
  /**
   * true (default) should NOT return the entity (204) after a PUT. false: return the entity (200).
   */
  put204?: boolean;
```
